name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Build
        working-directory: ./frontend
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.BACKEND_URL }}/api
          VITE_AWS_REGION: ${{ secrets.AWS_REGION }}
          VITE_USER_POOL_ID: ${{ secrets.AWS_COGNITO_USER_POOL_ID }}
          VITE_USER_POOL_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }}
          VITE_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          VITE_IDENTITY_POOL_ID: ${{ secrets.AWS_COGNITO_IDENTITY_POOL_ID }}
          VITE_SKIP_AWS_CONFIG: 'true'
          VITE_USE_MOCK_DATA: 'true'
          
      - name: Debug directory content
        run: |
          echo "Workspace root:"
          ls -la
          echo "Frontend directory:"
          ls -la frontend/
          echo "Build directory:"
          ls -la frontend/build/ || echo "Build directory not found"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run: aws s3 sync frontend/build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
        
      - name: Invalidate CloudFront cache
        if: success()
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 