name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: List files before build
        run: ls -la
        
      - name: Build
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.BACKEND_URL }}/api
          VITE_AWS_REGION: ${{ secrets.AWS_REGION }}
          VITE_USER_POOL_ID: ${{ secrets.AWS_COGNITO_USER_POOL_ID }}
          VITE_USER_POOL_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }}
          VITE_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          VITE_IDENTITY_POOL_ID: ${{ secrets.AWS_COGNITO_IDENTITY_POOL_ID }}
          VITE_SKIP_AWS_CONFIG: 'true'
          VITE_USE_MOCK_DATA: 'true'
          
      - name: List files after build
        run: |
          ls -la
          ls -la dist || echo "dist directory not found"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Debug AWS S3 bucket
        run: |
          echo "Using S3 bucket name ${S3_BUCKET_NAME}"
          aws s3 ls s3://${S3_BUCKET_NAME} || echo "Could not list bucket contents"
        env:
          S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
          
      - name: Upload to S3
        run: |
          if [ -d "dist" ]; then
            aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
          else
            echo "Error: dist directory does not exist. Build may have failed."
            exit 1
          fi
        
      - name: Invalidate CloudFront cache
        if: success()
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 